version: '3.8'

services:
  template:
    build: .
    command: npm run start:dev
    environment:
      - DB_TYPE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=template
      - PG_PORT=5432
      - PORT=3000
      - PG_HOST=db
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app/src

  db:
    container_name: template-db
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: template
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
